const api = 'https://us-central1-nih-nci-dceg-episphere-dev.cloudfunctions.net/';

export const getKey = async () => {
    const response = await fetch(api+'getKey');
    const data = await response.json();
    if(data.code === 200) {
        let obj = { access_token: data.access_token, token: data.token };
        localStorage.connectApp = JSON.stringify(obj);
    }
}

export const storeResponse = async (formData) => {
    formData.token = JSON.parse(localStorage.connectApp).token;
    const response = await fetch(api+'recruit/submit',
    {
        method: 'POST',
        headers:{
            Authorization:"Bearer "+JSON.parse(localStorage.connectApp).access_token,
            'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData)
    });
    return response.json();
}

export const sites = () => {
    return {
        1: 'HealthPartners',
        2: 'Henry Ford Health System',
        3: 'Kaiser Permanente Colorado',
        4: 'Kaiser Permanente Georgia',
        5: 'Kaiser Permanente Hawaii',
        6: 'Kaiser Permanente Northwest',
        7: 'Marshfield Clinic',
        8: 'Sanford Health',
        9: 'University of Chicago Medicine',
        13: 'Natiocal Cancer Institute',
        88: 'None of these'
    }
}

export const todaysDate = () => {
    const today = new Date();
    let dd = today.getDate();
    let mm = today.getMonth()+1; 
    const yyyy = today.getFullYear();
    if(dd<10) 
    {
        dd='0'+dd;
    } 

    if(mm<10) 
    {
        mm='0'+mm;
    } 
    return mm+'/'+dd+'/'+yyyy;
}

export const getparameters = (query) => {
    const array = query.split('&');
    let obj = {};
    array.forEach(value => {
        obj[value.split('=')[0]] = value.split('=')[1];
    });
    return obj;
}

export const allStates = {
    "Alabama":1,
    "Alaska":2,
    "Arizona":3,
    "Arkansas":4,
    "California":5,
    "Colorado":6,
    "Connecticut":7,
    "Delaware":8,
    "Florida":9,
    "Georgia":10,
    "Hawaii":11,
    "Idaho":12,
    "Illinois":13,
    "Indiana":14,
    "Iowa":15,
    "Kansas":16,
    "Kentucky":17,
    "Louisiana":18,
    "Maine":19,
    "Maryland":20,
    "Massachusetts":21,
    "Michigan":22,
    "Minnesota":23,
    "Mississippi":24,
    "Missouri":25,
    "Montana":26,
    "Nebraska":27,
    "Nevada":28,
    "New Hampshire":29,
    "New Jersey":30,
    "New Mexico":31,
    "New York":32,
    "North Carolina":33,
    "North Dakota":34,
    "Ohio":35,
    "Oklahoma":36,
    "Oregon":37,
    "Pennsylvania":38,
    "Rhode Island":39,
    "South Carolina":40,
    "South Dakota":41,
    "Tennessee":42,
    "Texas":43,
    "Utah":44,
    "Vermont":45,
    "Virginia":46,
    "Washington":47,
    "West Virginia":48,
    "Wisconsin":49,
    "Wyoming":50
}

export const allCountries = {
    "United States":1,
    "Afghanistan":2,
    "Albania":3,
    "Algeria":4,
    "Andorra":5,
    "Angola":6,
    "Antigua and Barbuda":7,
    "Argentina":8,
    "Armenia":9,
    "Australia":10,
    "Austria":11,
    "Azerbaijan":12,
    "The Bahamas":13,
    "Bahrain":14,
    "Bangladesh":15,
    "Barbados":16,
    "Belarus":17,
    "Belgium":18,
    "Belize":19,
    "Benin":20,
    "Bhutan":21,
    "Bolivia":22,
    "Bosnia and Herzegovina":23,
    "Botswana":24,
    "Brazil":25,
    "Brunei":26,
    "Bulgaria":27,
    "Burkina Faso":28,
    "Burundi":29,
    "Cabo Verde":30,
    "Cambodia":31,
    "Cameroon":32,
    "Canada":33,
    "Central African Republic":34,
    "Chad":35,
    "Chile":36,
    "China":37,
    "Colombia":38,
    "Comoros":39,
    "Congo, Democratic Republic of the":40,
    "Congo, Republic of the":41,
    "Costa Rica":42,
    "Côte d’Ivoire":43,
    "Croatia":44,
    "Cuba":45,
    "Cyprus":46,
    "Czech Republic":47,
    "Denmark":48,
    "Djibouti":49,
    "Dominica":50,
    "Dominican Republic":51,
    "East Timor (Timor-Leste)":52,
    "Ecuador":53,
    "Egypt":54,
    "El Salvador":55,
    "Equatorial Guinea":56,
    "Eritrea":57,
    "Estonia":58,
    "Eswatini":59,
    "Ethiopia":60,
    "Fiji":61,
    "Finland":62,
    "France":63,
    "Gabon":64,
    "The Gambia":65,
    "Georgia":66,
    "Germany":67,
    "Ghana":68,
    "Greece":69,
    "Grenada":70,
    "Guatemala":71,
    "Guinea":72,
    "Guinea-Bissau":73,
    "Guyana":74,
    "Haiti":75,
    "Honduras":76,
    "Hungary":77,
    "Iceland":78,
    "India":79,
    "Indonesia":80,
    "Iran":81,
    "Iraq":82,
    "Ireland":83,
    "Israel":84,
    "Italy":85,
    "Jamaica":86,
    "Japan":87,
    "Jordan":88,
    "Kazakhstan":89,
    "Kenya":90,
    "Kiribati":91,
    "Korea, North":92,
    "Korea, South":93,
    "Kosovo":94,
    "Kuwait":95,
    "Kyrgyzstan":96,
    "Laos":97,
    "Latvia":98,
    "Lebanon":99,
    "Lesotho":100,
    "Liberia":101,
    "Libya":102,
    "Liechtenstein":103,
    "Lithuania":104,
    "Luxembourg":105,
    "Madagascar":106,
    "Malawi":107,
    "Malaysia":108,
    "Maldives":109,
    "Mali":110,
    "Malta":111,
    "Marshall Islands":112,
    "Mauritania":113,
    "Mauritius":114,
    "Mexico":115,
    "Micronesia, Federated States of":116,
    "Moldova":117,
    "Monaco":118,
    "Mongolia":119,
    "Montenegro":120,
    "Morocco":121,
    "Mozambique":122,
    "Myanmar (Burma)":123,
    "Namibia":124,
    "Nauru":125,
    "Nepal":126,
    "Netherlands":127,
    "New Zealand":128,
    "Nicaragua":129,
    "Niger":130,
    "Nigeria":131,
    "North Macedonia":132,
    "Norway":133,
    "Oman":134,
    "Pakistan":135,
    "Palau":136,
    "Panama":137,
    "Papua New Guinea":138,
    "Paraguay":139,
    "Peru":140,
    "Philippines":141,
    "Poland":142,
    "Portugal":143,
    "Qatar":144,
    "Romania":145,
    "Russia":146,
    "Rwanda":147,
    "Saint Kitts and Nevis":148,
    "Saint Lucia":149,
    "Saint Vincent and the Grenadines":150,
    "Samoa":151,
    "San Marino":152,
    "Sao Tome and Principe":153,
    "Saudi Arabia":154,
    "Senegal":155,
    "Serbia":156,
    "Seychelles":157,
    "Sierra Leone":158,
    "Singapore":159,
    "Slovakia":160,
    "Slovenia":161,
    "Solomon Islands":162,
    "Somalia":163,
    "South Africa":164,
    "Spain":165,
    "Sri Lanka":166,
    "Sudan":167,
    "Sudan, South":168,
    "Suriname":169,
    "Sweden":170,
    "Switzerland":171,
    "Syria":172,
    "Taiwan":173,
    "Tajikistan":174,
    "Tanzania":175,
    "Thailand":176,
    "Togo":177,
    "Tonga":178,
    "Trinidad and Tobago":179,
    "Tunisia":180,
    "Turkey":181,
    "Turkmenistan":182,
    "Tuvalu":183,
    "Uganda":184,
    "Ukraine":185,
    "United Arab Emirates":186,
    "United Kingdom":187,
    "Uruguay":188,
    "Uzbekistan":189,
    "Vanuatu":190,
    "Vatican City":191,
    "Venezuela":192,
    "Vietnam":193,
    "Yemen":194,
    "Zambia":195,
    "Zimbabwe":196
}